{% set name = "rerun-c3d" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Ipuch/rerun-c3d/archive/{{ version }}.tar.gz
  sha256: a452fd9361542a190bed2598d25a05e9aa6c147d3e3afd7483ef74136272ba2d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - ezc3d
    - rerun-sdk
    - numpy

test:
  imports:
    - bionc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Ipuch/rerun-c3d
  summary: 'Display c3d from python'
  description: |
    Rerun C3D is a tool to rerun the C3D file and display its original content..
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/Ipuch/rerun-c3d

extra:
  recipe-maintainers:
    - ipuch
