{% set name = "rerun-c3d" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Ipuch/rerun-c3d/archive/{{ version }}.tar.gz
  sha256: 6791bd670efd086c99706c6dd82ba2d4dcee397a575c51f257398c8028f616be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - ezc3d
    - rerun-sdk

test:
  imports:
    - bionc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Ipuch/rerun-c3d
  summary: 'Display c3d from python'
  description: |
    Rerun C3D is a tool to rerun the C3D file and display its original content..
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/Ipuch/rerun-c3d

extra:
  recipe-maintainers:
    - ipuch
